"""add_workspace_id_to_file_metadata

Revision ID: 879fb5a39b2f
Revises: 77b4b28402b1
Create Date: 2025-06-11 02:33:13.719255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879fb5a39b2f'
down_revision: Union[str, None] = '77b4b28402b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('workspace_id', sa.Integer(), nullable=True))
    # Note: Foreign key constraint will be enforced by SQLAlchemy ORM
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'workspace_id')
    # ### end Alembic commands ###
