#!/usr/bin/env python3
"""
Development Server - Generated by Archon
"""

import sys
import os
from pathlib import Path

# Add the project root to the Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

try:
    from fastapi import FastAPI
    from fastapi.middleware.cors import CORSMiddleware
    import uvicorn
    
    # Import Archon-generated components
    from backend.core.auth.manager import auth_manager
    from backend.core.database.manager import DatabaseManager
    
    def create_app():
        """Create FastAPI application with Archon components"""
        app = FastAPI(
            title="BlueBirdHub",
            description="AI-Powered Document Management System (Enhanced by Archon)",
            version="1.0.0"
        )
        
        # Add CORS middleware
        app.add_middleware(
            CORSMiddleware,
            allow_origins=["*"],  # Configure appropriately for production
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )
        
        # Initialize database
        db_manager = DatabaseManager.get_instance()
        
        @app.get("/health")
        async def health_check():
            return {"status": "healthy", "enhanced_by": "archon"}
        
        @app.get("/auth/test")
        async def test_auth():
            return {"auth_manager": "initialized", "status": "ready"}
        
        return app
    
    if __name__ == "__main__":
        app = create_app()
        print("🚀 Starting BlueBirdHub development server (Enhanced by Archon)")
        print("📡 Server will be available at: http://localhost:8000")
        print("📄 API documentation: http://localhost:8000/docs")
        
        uvicorn.run(
            app, 
            host="0.0.0.0", 
            port=8000, 
            reload=True,
            log_level="info"
        )
        
except ImportError as e:
    print(f"❌ Import error: {e}")
    print("Make sure dependencies are installed: pip install -r requirements-archon.txt")
    sys.exit(1)
