#!/usr/bin/env python3
"""
Database Initialization Script - Generated by Archon
"""

import sys
import os
from pathlib import Path

# Add the project root to the Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

try:
    from backend.core.database.manager import DatabaseManager, Base
    
    def init_database():
        """Initialize database with Archon's recommendations"""
        print("🗄️  Initializing database...")
        
        # Create database manager instance
        db_manager = DatabaseManager.get_instance()
        
        # Create all tables
        db_manager.init_models()
        
        print("✅ Database initialized successfully")
        
    if __name__ == "__main__":
        init_database()
        
except ImportError as e:
    print(f"❌ Import error: {e}")
    print("Make sure dependencies are installed: pip install -r requirements-archon.txt")
    sys.exit(1)
