#!/usr/bin/env python3
"""
AI Framework Test Script - Generated by Archon
"""

import sys
import os
import asyncio
from pathlib import Path

# Add the project root to the Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root / "src"))

try:
    from backend.core.ai_services.framework import create_ai_orchestrator
    
    async def test_ai_framework():
        """Test the Archon-generated AI framework"""
        print("🤖 Testing AI framework...")
        
        try:
            orchestrator = create_ai_orchestrator()
            
            # Test content analysis
            test_content = "This is a test document for AI analysis."
            result = await orchestrator.analyze_with_fallback(test_content)
            
            print(f"✅ AI analysis successful: {result}")
            
        except Exception as e:
            print(f"⚠️  AI framework test failed: {e}")
            print("Make sure to set your AI provider API keys in .env")
    
    if __name__ == "__main__":
        asyncio.run(test_ai_framework())
        
except ImportError as e:
    print(f"❌ Import error: {e}")
    print("Make sure dependencies are installed: pip install -r requirements-archon.txt")
    sys.exit(1)
